### ISSUE TITLE
Touch pan enabled with 2 successive touches instead of simultaneous

### ISSUE THREAD

**Issue by ghybs** [elmarquis/Leaflet.GestureHandling#1]
Hi,

Very nice to have wrapped your solution in a Leaflet plugin!

When trying the demo page, I am still getting stuck in map navigation after having single touched the map twice successively, whereas touch panning is expected to be enabled only for 2 simultaneous touches.

I am using Chrome mobile on Android 7.

Scroll the page as instructed, scrolling at least once starting the scroll in the map viewport. As expected, the map does not pan, but the whole page scrolls. Release the finger.

I have not seen any overlay message at this point, not sure if it is already implemented.

Then continue trying to scroll, starting the touch again on the map viewport. This time, the map pans like the standard Leaflet behaviour.

**Comment by elmarquis** [comment]
I see what you mean. It’s not responding to the touch handlers at all. Thanks for pointing it out. Seems to just be Chrome for Android, as it works correctly on chrome for iOS and also safari. I’ll look into getting a fix up.

**Comment by ghybs** [comment]
Hi,

It looks much better now indeed, thanks!

There is just the "edge" case of starting a 1 finger touch, seeing the message overlay, then adding a 2nd finger (while the 1st one was continuously down). In thiscase, I see the message overlay disappear but the map panning does not come into play, I am still in page scrolling mode.
Maybe we could ignore this case for now?

Even more "edgy": on a laptop with touchpad, scroll the page (using 2 fingers) over the map viewport to make the message overlay appear. While the 2 fingers are still down, start pressing the "Ctrl" key (as instructed by the message). The map zoom now takes over, but there might be a slight delay, because most of the time, the browser has time to interpret the Ctrl + scroll as a page zoom/scale change, going to 90 or 110% depending on the scroll direction.

**Comment by ghybs** [comment]
Another side note: you can save the hassle of maintaining a separate `gh-pages` branch just for the sake of publishing GitHub Pages, by changing the settings of your repo to use the `master` branch (or a `/docs` folder of this branch) as the source of your Pages:
https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/

This is particularly suitable for small repos that do not mind committing dist / built files in the main branch.

**Comment by elmarquis** [comment]
@ghybs This is all really useful. And thank you for the github pages tip.
