### ISSUE TITLE
Disable Interactions

### ISSUE THREAD

**Issue by RyanMulready** [elmarquis/Leaflet.GestureHandling#18]
At certain points I would like to temporarily disable interactions.  Typically this would be done like so `map.dragging.disable()` and then `map.dragging.enable()` is it possible to do the same thing with this plugin installed?

**Comment by elmarquis** [comment]
You're going to find that this plugin takes over a bit when it comes to enabling and disabling dragging.

One solution could be to also deactivate the plugin at those points in your code.

```
// Deactivate the plugin
map.gestureHandling.disable();

// Do your own enabling / disabling of dragging
map.dragging.enable();
```

Let me know if there's anything you think the plugin could do to help you more in your situation. e.g: Would callbacks when the message is about to be shown/hidden be of use?

**Comment by RyanMulready** [comment]
Thank you for the response, a helper function would be better but this approach does work.  Something like this:

```
map.gestureHandling.dragging.disable()
```

Would be preferable.
