### ISSUE TITLE
 Leaflet.GestureHandling isn't working with Leaflet v.1.7.1

### ISSUE THREAD

**Issue by danielmalmros** [elmarquis/Leaflet.GestureHandling#58]
Hi there,

Thanks for this great plugin to Leaflet that makes it easy to display simple gestures.
We are actively using this plugin in our Angular 9 application and recently updated Leaflet to the newest version which we had to downgrade again due to _Leaflet.GestureHandling_ not working with that version.

The latest version of Leaflet has been released on September 4, 2020, and comes with some fixes to touchscreens that might affect the use of this plugin. See release here: https://leafletjs.com/2020/09/04/leaflet-1.7.1.html

**Steps to reproduce:**
1. Update Leaflet package from 1.6.0 to 1.7.1
2. See that no error's occurred but _Leaflet.GestureHandling_ no longer works.

Looking forward to seeing the plugin getting updated :)

**Comment by bartfeenstra** [comment]
I can confirm that this plugin doesn't work with Leaflet 1.7.x. The console does indeed not show any errors, but none of the gesture handling works, and the original Leaflet behavior is left intact (zoom on scroll).

**Comment by j0Shi82** [comment]
Duplicate of https://github.com/elmarquis/Leaflet.GestureHandling/issues/56

The fix has been successfully merged, but no new version has been released. Until that happens you can use
```
"leaflet-gesture-handling": "j0Shi82/Leaflet.GestureHandling#9d81d7b25e8b158ff56699931613edaa9e2239cf",
```
or 
```
"leaflet-gesture-handling": "elmarquis/Leaflet.GestureHandling#1592dd52ffe81f6030bb714731c2408973f30a80",
```
in your package.json.

**Comment by elmarquis** [comment]
Thanks and sorry for delay. This has now been updated and published

**Comment by danielmalmros** [comment]
I can confirm that it works after recent update, thanks!
