### ISSUE TITLE
Text about Ctrl + scroll confusing

### ISSUE THREAD

**Issue by Allmedialab** [elmarquis/Leaflet.GestureHandling#9]
Hi,
I think the text about Ctrl + scroll would be more clear if you say:
"Use Ctrl and scroll to zoom the map!"
Now it looks like you have to use Ctrl and + and scroll. "Ctrl +" and "Ctrl -" are zoom functions on multiple applications.
Regards,
David

**Comment by adomas187** [comment]
For me the text seems not confusing. Anyway you can change to custom text like this:
```
    gestureHandlingText: {
        touch: "Use two fingers to move the map",
        scroll: "Use CTRL and Scroll to zoom the map",
    }
```

**Comment by elmarquis** [comment]
Valid enough point. Some may agree some disagree.

The reason I'd probably not change it is there's 52 language translations based on: "Use Ctrl + scroll to zoom the map". I was only able to achieve that by keeping the wording the exact same as google uses in it's implementation.

**Comment by elmarquis** [comment]
Marking as closed as changes to text aren't likely to happen due to translation requirement and as pointed out, the option has been provided to override it.
